/** Paper Signal reminder: Scratch Sheet is a private local canvas, built with explicit marks and no remote service. */
const api = globalThis.browser ?? globalThis.chrome;
const prefix = "annotaura:project:scratch:";
const board = document.querySelector("#board"), group = document.querySelector("#annotations"), nameInput = document.querySelector("#sheet-name");
const state = { project:null, tool:"select", settings:{ color:"#FFB000", width:4, opacity:.72 }, drawing:null, selectedId:null, drag:null, undo:[], redo:[] };
const palette = ["#18201E", "#FFB000", "#B84C3D", "#315F79", "#315E4B", "#6950A1"];
const esc = (value) => String(value).replace(/[<>&"']/g, (char) => ({"<":"&lt;",">":"&gt;","&":"&amp;","\"":"&quot;","'":"&apos;"})[char]);
const uid = () => `ann_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const activeLayer = () => state.project.layers.find((layer) => layer.id === "marks");
function allAnnotations() { return state.project.layers.flatMap((layer) => layer.annotations.map((annotation) => ({...annotation,layerId:layer.id}))); }
function find(id) { return allAnnotations().find((item) => item.id === id); }
function p(event) { const rect = board.getBoundingClientRect(); return { x:Math.round((event.clientX-rect.left)*(board.viewBox.baseVal.width/rect.width)), y:Math.round((event.clientY-rect.top)*(board.viewBox.baseVal.height/rect.height)) }; }
function toast(message) { const node=document.querySelector("#toast"); node.textContent=message; node.classList.add("is-visible"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>node.classList.remove("is-visible"),2400); }
function snap() { state.undo.push(JSON.stringify(state.project.layers)); state.undo=state.undo.slice(-60); state.redo=[]; }
function restore(serialized) { state.project.layers=JSON.parse(serialized); render(); }
async function save(show=false) { state.project.name=nameInput.value.trim()||"Untitled scratch sheet"; state.project.updatedAt=new Date().toISOString(); await api.storage.local.set({[`${prefix}${state.project.id}`]:state.project}); if(show) toast("Scratch sheet saved locally."); }
function saveSoon() { clearTimeout(saveSoon.timer); saveSoon.timer=setTimeout(()=>save(false),300); }
function render() { renderLayer(); document.querySelectorAll("[data-tool]").forEach((node)=>node.classList.toggle("is-active",node.dataset.tool===state.tool)); document.querySelector("#color-value").textContent=state.settings.color; document.querySelector("#width-value").textContent=`${state.settings.width}px`; document.querySelector("#opacity-value").textContent=`${Math.round(state.settings.opacity*100)}%`; }
function renderLayer() { group.innerHTML=allAnnotations().map(svg).join(""); }
function patchElement(a) { const node=group.querySelector(`[data-id="${a.id}"]`); if(!node){renderLayer();return;} const g=a.geometry; if(a.type==="path"||a.type==="highlight"){node.setAttribute("d",g.points.map((q,i)=>`${i?"L":"M"}${q.x} ${q.y}`).join(" "));return;} if(a.type==="text"||a.type==="stamp"){node.setAttribute("transform",`translate(${g.x} ${g.y})`);return;} const x=Math.min(g.x1,g.x2),y=Math.min(g.y1,g.y2),w=Math.abs(g.x2-g.x1),h=Math.abs(g.y2-g.y1); if(a.type==="rect"){node.setAttribute("x",x);node.setAttribute("y",y);node.setAttribute("width",w);node.setAttribute("height",h);return;} if(a.type==="ellipse"){node.setAttribute("cx",x+w/2);node.setAttribute("cy",y+h/2);node.setAttribute("rx",w/2);node.setAttribute("ry",h/2);return;} node.setAttribute("x1",g.x1);node.setAttribute("y1",g.y1);node.setAttribute("x2",g.x2);node.setAttribute("y2",g.y2); }
function svg(a) { const c=`class="annotation" data-id="${a.id}" data-selected="${a.id===state.selectedId}" opacity="${a.style.opacity}"`; const g=a.geometry; if(a.type==="path"||a.type==="highlight") return `<path ${c} d="${g.points.map((q,i)=>`${i?"L":"M"}${q.x} ${q.y}`).join(" ")}" fill="none" stroke="${a.style.color}" stroke-width="${a.style.width}" stroke-linecap="round" stroke-linejoin="round" pointer-events="stroke"/>`; if(a.type==="text") return `<g ${c} transform="translate(${g.x} ${g.y})" pointer-events="all"><rect x="-8" y="-23" width="${Math.max(80,Math.min(300,a.text.length*8+18))}" height="34" fill="#F6F0E4" stroke="${a.style.color}" stroke-width="1.5"/><text x="0" y="0" fill="#18201E" font-family="Space Grotesk,sans-serif" font-size="14">${esc(a.text)}</text></g>`; if(a.type==="stamp") return `<g ${c} transform="translate(${g.x} ${g.y})" pointer-events="all"><circle r="16" fill="#F6F0E4" stroke="${a.style.color}" stroke-width="3"/><text text-anchor="middle" dominant-baseline="central" fill="#18201E" font-family="IBM Plex Mono,monospace" font-size="14" font-weight="700">${esc(a.text)}</text></g>`; const x=Math.min(g.x1,g.x2),y=Math.min(g.y1,g.y2),w=Math.abs(g.x2-g.x1),h=Math.abs(g.y2-g.y1); if(a.type==="rect") return `<rect ${c} x="${x}" y="${y}" width="${w}" height="${h}" fill="${a.style.color}" fill-opacity=".12" stroke="${a.style.color}" stroke-width="${a.style.width}" pointer-events="all"/>`; if(a.type==="ellipse") return `<ellipse ${c} cx="${x+w/2}" cy="${y+h/2}" rx="${w/2}" ry="${h/2}" fill="${a.style.color}" fill-opacity=".12" stroke="${a.style.color}" stroke-width="${a.style.width}" pointer-events="all"/>`; return `<line ${c} x1="${g.x1}" y1="${g.y1}" x2="${g.x2}" y2="${g.y2}" stroke="${a.style.color}" stroke-width="${a.style.width}" stroke-linecap="round" ${a.type==="arrow"?"marker-end=\"url(#arrow)\"":""} pointer-events="stroke"/>`; }
function make(toolType,start) { const style={color:state.settings.color,width:toolType==="highlight"?Math.max(14,state.settings.width*5):state.settings.width,opacity:toolType==="highlight"?Math.min(.36,state.settings.opacity):state.settings.opacity}; const type=toolType==="pen"?"path":toolType; return {id:uid(),type,style,createdAt:new Date().toISOString(),geometry:(toolType==="pen"||toolType==="highlight")?{points:[start]}:{x1:start.x,y1:start.y,x2:start.x,y2:start.y}}; }
function translate(a,dx,dy) { const g=a.geometry; if(a.type==="path"||a.type==="highlight") g.points=g.points.map((q)=>({x:q.x+dx,y:q.y+dy})); else if(a.type==="text"||a.type==="stamp") {g.x+=dx;g.y+=dy;} else {g.x1+=dx;g.y1+=dy;g.x2+=dx;g.y2+=dy;} }
function tool(toolName) { state.tool=toolName; state.selectedId=null; board.style.cursor=toolName==="text"?"text":toolName==="select"?"default":"crosshair"; render(); }
board.addEventListener("pointerdown",(event)=>{ if(event.button!==0)return; const hit=event.target.closest?.("[data-id]"); if(state.tool==="select") { if(hit) {state.selectedId=hit.dataset.id;state.drag={id:state.selectedId,start:p(event),before:JSON.stringify(state.project.layers),origin:JSON.parse(JSON.stringify(find(hit.dataset.id)?.geometry||{}))};board.setPointerCapture(event.pointerId);} else state.selectedId=null; render(); return; } const start=p(event); if(state.tool==="text") { const text=prompt("Write an annotation note:"); if(text?.trim()){snap(); state.project.layers.find((l)=>l.id==="notes").annotations.push({id:uid(),type:"text",text:text.trim(),style:{color:state.settings.color,width:state.settings.width,opacity:1},geometry:start,createdAt:new Date().toISOString()});saveSoon();render();}return;} if(state.tool==="stamp"){snap();const layer=state.project.layers.find((l)=>l.id==="evidence");layer.annotations.push({id:uid(),type:"stamp",text:String(layer.annotations.filter((a)=>a.type==="stamp").length+1),style:{color:state.settings.color,width:state.settings.width,opacity:1},geometry:start,createdAt:new Date().toISOString()});saveSoon();render();return;} snap(); const annotation=make(state.tool,start);activeLayer().annotations.push(annotation);state.drawing={annotation,pointerId:event.pointerId};board.setPointerCapture(event.pointerId);render();});
board.addEventListener("pointermove",(event)=>{ if(state.drag){const current=p(event);const {id,start,origin}=state.drag;const annotation=find(id);if(annotation&&origin){annotation.geometry=JSON.parse(JSON.stringify(origin));translate(annotation,current.x-start.x,current.y-start.y);patchElement(annotation);}return;} if(!state.drawing)return;const annotation=state.drawing.annotation,current=p(event);if(annotation.type==="path"||annotation.type==="highlight")annotation.geometry.points.push(current);else{annotation.geometry.x2=current.x;annotation.geometry.y2=current.y;}patchElement(annotation);});
board.addEventListener("pointerup",()=>{ if(state.drag){state.undo.push(state.drag.before);state.undo=state.undo.slice(-60);state.redo=[];state.drag=null;saveSoon();render();return;}if(!state.drawing)return;const a=state.drawing.annotation;if((a.type==="path"||a.type==="highlight")&&a.geometry.points.length<2)activeLayer().annotations=activeLayer().annotations.filter((x)=>x.id!==a.id);state.drawing=null;saveSoon();render();});
function undo(){const old=state.undo.pop();if(!old){toast("Nothing to undo.");return;}state.redo.push(JSON.stringify(state.project.layers));restore(old);saveSoon();}function redo(){const next=state.redo.pop();if(!next){toast("Nothing to redo.");return;}state.undo.push(JSON.stringify(state.project.layers));restore(next);saveSoon();}
function del(){if(!state.selectedId){toast("Select an annotation first.");return;}snap();for(const layer of state.project.layers)layer.annotations=layer.annotations.filter((a)=>a.id!==state.selectedId);state.selectedId=null;saveSoon();render();}
function exportProject(){const data=JSON.stringify({format:"annotaura-project",version:"1.0",exportedAt:new Date().toISOString(),project:state.project},null,2),url=URL.createObjectURL(new Blob([data],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`annotaura-${state.project.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")||"scratch"}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("Scratch sheet exported.");}
function configure(){const swatches=document.querySelector("#swatches");palette.forEach((color)=>{const button=document.createElement("button");button.style.background=color;button.title=color;button.addEventListener("click",()=>{state.settings.color=color;document.querySelector("#color").value=color;configure();render();});swatches.append(button);});swatches.querySelectorAll("button").forEach((button)=>button.classList.toggle("is-active",button.title===state.settings.color));}
document.querySelectorAll("[data-tool]").forEach((button)=>button.addEventListener("click",()=>tool(button.dataset.tool)));document.querySelector("#undo").addEventListener("click",undo);document.querySelector("#redo").addEventListener("click",redo);document.querySelector("#delete").addEventListener("click",del);document.querySelector("#export").addEventListener("click",exportProject);nameInput.addEventListener("change",()=>save(true));document.querySelector("#color").addEventListener("input",(e)=>{state.settings.color=e.target.value;configure();render();});document.querySelector("#width").addEventListener("input",(e)=>{state.settings.width=Number(e.target.value);render();});document.querySelector("#opacity").addEventListener("input",(e)=>{state.settings.opacity=Number(e.target.value)/100;render();});
function physicalLetter(e){const m=/^Key([A-Z])$/.exec(e.code||"");if(m)return m[1].toLowerCase();const k=e.key.toLowerCase();return /^[a-z]$/.test(k)?k:null;}
document.addEventListener("keydown",(e)=>{const tag=e.target?.tagName;if(tag==="INPUT"||tag==="TEXTAREA"||tag==="SELECT"||e.target?.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&physicalLetter(e)==="z"){e.preventDefault();e.shiftKey?redo():undo();return;}if((e.ctrlKey||e.metaKey)&&physicalLetter(e)==="y"){e.preventDefault();redo();return;}if((e.key==="Delete"||e.key==="Backspace")&&state.selectedId){e.preventDefault();del();return;}const map={s:"select",p:"pen",h:"highlight",t:"text",l:"line",a:"arrow",r:"rect",o:"ellipse",e:"stamp"};const letter=physicalLetter(e);if(!e.altKey&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&letter&&map[letter]){e.preventDefault();tool(map[letter]);}});
(async()=>{const id=new URLSearchParams(location.search).get("id");const all=await api.storage.local.get(null);state.project=Object.values(all).find((value)=>value?.kind==="scratch"&&value.id===id);if(!state.project){toast("Scratch sheet not found. Return to the Workspace to create one.");state.project={id:`scratch_${Date.now().toString(36)}`,kind:"scratch",name:"Untitled scratch sheet",layers:["marks","notes","evidence"].map((id)=>({id,name:id[0].toUpperCase()+id.slice(1),visible:true,annotations:[]}))};}nameInput.value=state.project.name;configure();render();})();
